<?php
/**
 Paywall module to control non-subscriber access
*/


/**
 * add admin url
 * @return array
 */
function etype_paywall_menu() {
    $items['admin/config/etype/etype_paywall/settings'] = [
        'title' => 'Paywall Settings',
        'description' => 'eType paywall options.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('etype_paywall_admin'),
        'access arguments' => array('administer paywall'),
        'file' => 'includes/etype_paywall.admin.inc',
        'type' => MENU_NORMAL_ITEM,
    ];
    return $items;
}

/**
 * Implements hook_permission().
 */
function etype_paywall_permission() {
    return [
        'administer paywall' => [
            'title' => t('Administer Paywall'),
        ],
    ];
}

/**
 * @param $vars
 */
function etype_paywall_preprocess_html(&$vars) {

    if (user_is_logged_in()) {
        drupal_add_js(array('etype_paywall' => array('erase' => 1)), array('type' => 'setting'));
    } else {
        //dpm($vars['classes_array']);
        // Check for node using body class
        if (in_array('node-type-article', $vars['classes_array'])) {
            $limit = variable_get('etype_paywall_limit',4);
            drupal_add_js(array('etype_paywall' => array('limit' => $limit)), array('type' => 'setting'));
            $duration = variable_get('etype_paywall_duration',4);
            drupal_add_js(array('etype_paywall' => array('duration' => $duration)), array('type' => 'setting'));
            drupal_add_js(array('etype_paywall' => array('erase' => 0)), array('type' => 'setting'));
            drupal_add_js(drupal_get_path('module', 'etype_paywall') . '/js/etype_paywall.js', [
                'group' => JS_THEME,
                'scope' => 'footer',
            ]);
            drupal_add_css(drupal_get_path('module', 'etype_paywall') . '/css/etype_paywall.css');
        }
    }
}

/**
 * Implements hook_block_info().
 */
function etype_paywall_block_info() {
    $blocks = [];
    $blocks['etype-paywall'] = [
        'info' => t('eType Paywall'),
    ];
    return $blocks;
}

/**
 * Implements hook_block_view()
 * @param string $delta
 * @return array
 */
function etype_paywall_block_view($delta = '') {
    $block = [];
    switch ($delta) {
        case 'etype-paywall':
            $content = check_markup(variable_get('etype_paywall_block_content')['value'], 'full_html');
            $block['subject'] = '';
            $block['content'] = $content;
            break;
    }
    return $block;
}